---
title: "Projects"
listing:
  contents: projects
  type: grid
  categories: false
---

1. 2024-2025      Rhododendron Research Network grant from the American Rhododendron Society. 

2. 2023-2024      Underground explorers research grant from Society for the Protection of Underground Networks (SPUN) https://www.spun.earth/.

3. 2021-2023	Marie Skłodowska-Curie Action Individual Fellowship , awarded under Horizon 2020 from the European Union, Grant No: 101038052.

4. 2015-2018	Senior Research Fellowship, awarded by University Grants commission, India.

5. 2013-2015	Junior Research Fellowship, awarded by University Grants commission, India.


•	Other contributions to the research community
Since 2019   Multiple open trait dataset submissions (e.g., Try, Dryad and Zenodo repositories) from globally underrepresented region i.e., Himalaya as well as from other experimental works including metabolomic datasets.
2024 	Participant in Rhododendron Research Network
2023	Participated as Underground Explorer in Society for the Protection of Underground Networks (SPUN) and submitted a belowground biodiversity (bacterial and fungal) dataset from Himalayan region.
2022 	Contributor to “Splots and SoilTemp” research networks. Contribution includes plant abundance, functional trait and climate datasets from unexplored high elevations of Himalaya – 2 research articles (as co-author) stemming from this are under review revision phase.


