---
title: Publications
---
["Link to ORCID ID"](https://orcid.org/0000-0002-4610-5444)

["Link to Google Scholar"](https://scholar.google.co.in/citations?user=OPzKV_0AAAAJ&hl=en)



**Thakur D**, Rathore N, Jandová V, Münzbergová Z, Dolezal J (2025). ["Shift from acquisitive to conservative plant strategies with increasing drought and temperature extremes in an alpine shrub"](https://doi.org/10.1101/2025.06.26.661801). Preprint, BioRxiv. Accepted in Annals of Botany. https://doi.org/10.1101/2025.06.26.661801

Banerjee S, Rathore N, Semerád J, Cajthaml T, Münzbergová Z, **Thakur D**. (2025). ["Soil moisture and its interaction with temperature determine root metabolomes of a Himalayan alpine shrub"](https://doi.org/10.1111/ppl.70444). Physiologia Plantarum.https://doi.org/10.1111/ppl.70444

Manavalan, M, **Thakur, D**, Schaumberger, A, Bahn, M, & Münzbergová, Z. (2025). ["Global Change Factors differentially impact Floral and Leaf Economic Traits"](https://doi.org/10.1101/2025.05.15.654190). Preprint, BioRxiv. Accepted in Annals of Botany. https://doi.org/10.1101/2025.05.15.654190

**Thakur, D.**, & Chawla, A. (2025).["Aspect outweighs elevation in influencing plant functioning at high elevations of Himalaya"](comming soon), Accepted in Plant Ecology - Coming soon

Bhatt, T., Rathore, N., Semerad, J., Cajthaml, T., **Thakur, D.**, & Munzbergova, Z. (2025). ["Drought and methyl jasmonate memory interact to determine plant functioning under current drought stress in a perennial grass"](https://doi.org/10.1101/2025.08.03.668340). Preprint, BioRxiv, 2025.08.03.668340. https://doi.org/10.1101/2025.08.03.668340

Bhatt, T., and **Thakur, D.**, and Munzbergova, Z. (2025) ["Unveiling the Interactive Dynamics: Recurring Drought, Methyl Jasmonate, and Plant Performance in a Perennial Grass"](http://dx.doi.org/10.2139/ssrn.5070067). BioRxiv Preprint. Also Available at SSRN: https://ssrn.com/abstract=5070067.

Rathore, N., Hanzelková, V., Dostálek, T., **Thakur, D.**, & Münzbergová, Z. (2025). ["Invasive species are more homogenous in their root morphology and exudate metabolome than non-invasive alien species"](https://doi.org/10.1016/J.ENVEXPBOT.2024.106057). Environmental and Experimental Botany, 229, 106057. https://doi.org/10.1016/J.ENVEXPBOT.2024.106057

**Thakur D.** et al. (2024). ["Global warming alters Himalayan alpine shrub growth dynamics and climate sensitivity"](https://www.sciencedirect.com/science/article/pii/S0048969724003875). Science of the Total Environment, 916:170252.  https://www.sciencedirect.com/science/article/pii/S0048969724003875

**Thakur, D.** et al. (2023). ["Differential effect of climate of origin and cultivation climate on structural and biochemical plant traits"](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/1365-2435.14291). Functional Ecology. 2023;37:1436–1448.https://besjournals.onlinelibrary.wiley.com/doi/10.1111/1365-2435.14291
	
**Thakur, D.**, & Münzbergová, Z. (2022). ["Rhizome trait scaling relationships are modulated by growth conditions and are linked to plant fitness"](https://academic.oup.com/aob/article/129/5/529/6532026). Annals of Botany, 129(5), 529–540. https://academic.oup.com/aob/article/129/5/529/6532026
	
**Thakur, D.**, Rathore, N., & Chawla, A. (2019). ["Increase in light interception cost and metabolic mass component of leaves are coupled for efficient resource use in the high altitude vegetation"](https://nsojournals.onlinelibrary.wiley.com/doi/full/10.1111/oik.05538). Oikos, 128(2), 254–263.https://nsojournals.onlinelibrary.wiley.com/doi/full/10.1111/oik.05538 
	
**Thakur, D.**, & Chawla, A. (2019). ["Functional diversity along elevational gradients in the high altitude vegetation of the western Himalaya"](https://link.springer.com/article/10.1007/s10531-019-01728-5). Biodiversity and Conservation, 28(8–9), 1977–1996. 
	
**Thakur, D.** et al. (2021). ["Identification of ecological factors affecting the occurrence and abundance of *Dactylorhiza hatagirea* (D.Don) Soo in the Himalaya"](https://doi.org/10.1016/j.jarmap.2020.100286). Journal of Applied Research on Medicinal and Aromatic Plants, 20(April 2020), 100286. https://doi.org/10.1016/j.jarmap.2020.100286
	
**Thakur, D.** Singh, L., & Chawla, A. (2020). ["Reliability of leaf functional traits after delayed measurements"](https://doi.org/10.1071/BT19166). Australian Journal of Botany, 68(2), 100–107. https://doi.org/10.1071/BT19166
	
Rathore, N., **Thakur, D.** et al. (2021). ["Time-series eco-metabolomics reveals extensive reshuffling in metabolome during transition from cold acclimation to de-acclimation in an alpine shrub"](https://doi.org/10.1111/ppl.13524). Physiologia Plantarum, 173(4), 1824–1840. 
	
Rathore, N., **Thakur, D.**, & Chawla, A. (2018). ["Seasonal variations coupled with elevation gradient drives significant changes in eco-physiological and biogeochemical traits of a high altitude evergreen broadleaf shrub, Rhododendron anthopogon"](https://doi.org/10.1016/j.plaphy.2018.08.009). Plant Physiology and Biochemistry, 132(May), 708–719. https://doi.org/10.1016/j.plaphy.2018.08.009
	
Singh, L., **Thakur, D.** et al. (2021). ["Dynamics of leaf litter decomposition in the timberline zone of western Himalaya"](https://doi.org/10.1016/j.actao.2021.103715). Acta Oecologica, 111, 103715.

**Thakur, D.** et al. (2018) ["Enhanced reproductive success revealed key strategy for persistence of devastated populations in Himalayan food-deceptive orchid, *Dactylorhiza hatagirea*"](https://doi.org/10.1111/1442-1984.12205). Plant Species Biology (2018) 33, 191–202.
